#: include Landing.kv
#: include Signup.kv
#: include Login.kv
#: include Home.kv
#: include Camera.kv
#: include editimage.kv
#: include Result.kv
#: include MedicalHistory.kv
#: import FadeTransition kivy.uix.screenmanager.FadeTransition
#: import main main
#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton
#: import Window kivy.core.window.Window